const mongoose=require('mongoose');
const {Schema} =mongoose;

const AdminSchema=new Schema({
    name:{
        type:String,
        required:true,
        default:"krutikshah"
    },
    label:{
        type:String,
        default:"admin" 
    },
    email:{
        type:String,
        required:true,
        default:"skrutik9@gmail.com"
    },
    password:{
        type:String,
        required:true,
        default:"krutik9702"
    },
    nooforders:{
        type:Number,
        default:0,
        required:false
    },
    amountofwaste:{
        type:Number,
        default:0,
        required:false
    },
    nooforganicwaste:{
        type:Number,
        default:0,
        required:false
    },
    amountoforganicwaste:{
        type:Number,
        default:0,
        required:false
    },
    noofhazardouswaste:{
        type:Number,
        default:0,
        required:false
    },
    amountofhazardouswaste:{
        type:Number,
        default:0,
        required:false
    },
    noofsolidwaste:{
        type:Number,
        default:0,
        required:false
    },
    amountofsolidwaste:{
        type:Number,
        default:0,
        required:false
    },
    noofliquidwaste:{
        type:Number,
        default:0,
        required:false
    },
    amountofliquidwaste:{
        type:Number,
        default:0,
        required:false
    },
    noofrecyclablewaste:{
        type:Number,
        default:0,
        required:false
    },
    amountofrecyclablewaste:{
        type:Number,
        default:0,
        required:false
    }


})
module.exports=mongoose.model('Admin',AdminSchema);